//! Provides HTTP and NASDAQ API clients for the downloader pipeline.
use crate::filetools::save_file;
use anyhow::{Context, Result, anyhow};
use bytes::Bytes;
use futures::Stream;
use reqwest::{
    Client, RequestBuilder,
    header::{
        ACCEPT, ACCEPT_ENCODING, ACCEPT_LANGUAGE, AUTHORIZATION, COOKIE, HeaderMap, HeaderName,
        HeaderValue, REFERER, USER_AGENT,
    },
};
use serde_json::Value;
use std::collections::HashMap;
use std::path::Path;
use std::time::Duration;
use tokio::time::sleep;

#[derive(Debug)]
pub struct HttpResponse {
    pub body: Bytes,
}

impl HttpResponse {
    /// Decodes the response body as UTF-8 text.
    ///
    /// # Failure
    /// Returns an error if the body is not valid UTF-8.
    pub fn into_text(self) -> Result<String> {
        String::from_utf8(self.body.to_vec())
            .map_err(|e| anyhow!("Failed to convert bytes to UTF-8 string: {}", e))
    }
}

fn http_client() -> &'static Client {
    static CLIENT: std::sync::OnceLock<Client> = std::sync::OnceLock::new();
    CLIENT.get_or_init(|| {
        Client::builder()
            .pool_max_idle_per_host(10)
            .pool_idle_timeout(Duration::from_secs(90))
            .build()
            .expect("Failed to create HTTP client")
    })
}

const CHROME_USER_AGENT: &str = concat!(
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) ",
    "AppleWebKit/537.36 (KHTML, like Gecko) ",
    "Chrome/145.0.0.0 Safari/537.36"
);
const CHROME_SEC_CH_UA: &str =
    r#""Not:A-Brand";v="99", "Google Chrome";v="145", "Chromium";v="145""#;
const CHROME_SEC_CH_UA_MOBILE: &str = "?0";
const CHROME_SEC_CH_UA_PLATFORM: &str = r#""Windows""#;

const SEC_CH_UA: HeaderName = HeaderName::from_static("sec-ch-ua");
const SEC_CH_UA_MOBILE: HeaderName = HeaderName::from_static("sec-ch-ua-mobile");
const SEC_CH_UA_PLATFORM: HeaderName = HeaderName::from_static("sec-ch-ua-platform");
const SEC_FETCH_DEST: HeaderName = HeaderName::from_static("sec-fetch-dest");
const SEC_FETCH_MODE: HeaderName = HeaderName::from_static("sec-fetch-mode");
const SEC_FETCH_SITE: HeaderName = HeaderName::from_static("sec-fetch-site");
const SEC_FETCH_USER: HeaderName = HeaderName::from_static("sec-fetch-user");
const PRIORITY: HeaderName = HeaderName::from_static("priority");
const UPGRADE_INSECURE_REQUESTS: HeaderName = HeaderName::from_static("upgrade-insecure-requests");

fn chrome_get_headers(url: &str, caller_headers: Option<&[(&str, &str)]>) -> Result<HeaderMap> {
    let mut caller_headers = parse_headers(caller_headers)?;
    let mut headers = HeaderMap::with_capacity(13 + caller_headers.len());

    // Keep this sequence aligned with surf's Chrome GET preset. HTTP/2 pseudo-headers
    // are generated by hyper/reqwest and must precede these regular headers on the wire.
    insert_header(
        &mut headers,
        &mut caller_headers,
        SEC_CH_UA,
        Some(CHROME_SEC_CH_UA),
    );
    insert_header(
        &mut headers,
        &mut caller_headers,
        SEC_CH_UA_MOBILE,
        Some(CHROME_SEC_CH_UA_MOBILE),
    );
    insert_header(
        &mut headers,
        &mut caller_headers,
        SEC_CH_UA_PLATFORM,
        Some(CHROME_SEC_CH_UA_PLATFORM),
    );
    insert_header(&mut headers, &mut caller_headers, AUTHORIZATION, None);
    insert_header(
        &mut headers,
        &mut caller_headers,
        UPGRADE_INSECURE_REQUESTS,
        Some("1"),
    );
    insert_header(
        &mut headers,
        &mut caller_headers,
        USER_AGENT,
        Some(CHROME_USER_AGENT),
    );
    insert_header(
        &mut headers,
        &mut caller_headers,
        ACCEPT,
        Some(
            "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
        ),
    );
    insert_header(
        &mut headers,
        &mut caller_headers,
        SEC_FETCH_SITE,
        Some("none"),
    );
    insert_header(
        &mut headers,
        &mut caller_headers,
        SEC_FETCH_MODE,
        Some("navigate"),
    );
    insert_header(
        &mut headers,
        &mut caller_headers,
        SEC_FETCH_USER,
        Some("?1"),
    );
    insert_header(
        &mut headers,
        &mut caller_headers,
        SEC_FETCH_DEST,
        Some("document"),
    );
    insert_header(
        &mut headers,
        &mut caller_headers,
        REFERER,
        referer_for_url(url),
    );
    insert_header(
        &mut headers,
        &mut caller_headers,
        ACCEPT_ENCODING,
        Some("gzip, deflate, br, zstd"),
    );
    insert_header(
        &mut headers,
        &mut caller_headers,
        ACCEPT_LANGUAGE,
        Some("en-US,en;q=0.9"),
    );
    insert_header(&mut headers, &mut caller_headers, COOKIE, None);
    insert_header(&mut headers, &mut caller_headers, PRIORITY, Some("u=0, i"));

    for (key, value) in caller_headers {
        headers.append(key, value);
    }

    Ok(headers)
}

fn get_request(
    url: &str,
    headers: Option<&[(&str, &str)]>,
    query: Option<&[(&str, &str)]>,
    timeout_secs: Option<u64>,
) -> Result<RequestBuilder> {
    let mut request_builder = http_client()
        .get(url)
        .headers(chrome_get_headers(url, headers)?);

    if let Some(timeout_secs) = timeout_secs {
        request_builder = request_builder.timeout(Duration::from_secs(timeout_secs));
    }

    if let Some(query) = query {
        request_builder = request_builder.query(query);
    }

    Ok(request_builder)
}

fn parse_headers(headers: Option<&[(&str, &str)]>) -> Result<Vec<(HeaderName, HeaderValue)>> {
    headers
        .unwrap_or_default()
        .iter()
        .map(|&(key, value)| {
            let key = HeaderName::from_bytes(key.as_bytes())
                .with_context(|| format!("invalid header name: {key}"))?;
            let mut value = HeaderValue::from_str(value)
                .with_context(|| format!("invalid value for header {key}"))?;
            if key == AUTHORIZATION || key == COOKIE {
                value.set_sensitive(true);
            }

            Ok((key, value))
        })
        .collect()
}

fn insert_header(
    headers: &mut HeaderMap,
    caller_headers: &mut Vec<(HeaderName, HeaderValue)>,
    key: HeaderName,
    default: Option<&'static str>,
) {
    if let Some(index) = caller_headers
        .iter()
        .position(|(caller_key, _)| caller_key == key)
    {
        let (_, value) = caller_headers.remove(index);
        headers.insert(key, value);
    } else if let Some(value) = default {
        headers.insert(key, HeaderValue::from_static(value));
    }
}

fn referer_for_url(url: &str) -> Option<&'static str> {
    if url.starts_with("https://data.nasdaq.com/") {
        Some("https://data.nasdaq.com/")
    } else if url.starts_with("https://img.logo.dev/") {
        Some("https://img.logo.dev/")
    } else {
        None
    }
}

/// Performs a GET request with optional headers and query parameters.
///
/// # Failure
/// Returns an error if all retry attempts fail or the response body cannot be read.
pub async fn http_get(
    url: &str,
    headers: Option<&[(&str, &str)]>,
    query: Option<&[(&str, &str)]>,
    retries: u32,
    timeout_secs: Option<u64>,
) -> Result<HttpResponse> {
    for attempt in 1..=retries {
        let result = get_request(url, headers, query, timeout_secs)?.send().await;

        match result {
            Ok(response) if response.status().is_success() => {
                match response.bytes().await {
                    Ok(body) => return Ok(HttpResponse { body }),
                    Err(e) if attempt == retries => {
                        return Err(anyhow!("Failed to read response body: {}", e));
                    }
                    _ => {} // Continue to retry
                }
            }
            Ok(response) if attempt == retries => {
                return Err(anyhow!(
                    "HTTP request failed with status {} after {} attempts",
                    response.status(),
                    retries
                ));
            }
            Err(e) if attempt == retries => {
                return Err(anyhow!("Request failed after {} attempts: {}", retries, e));
            }
            _ => {} // Continue to retry
        }

        if attempt < retries {
            let delay_secs = 2_u64.pow(attempt - 1); // 1s, 2s, 4s, 8s...
            sleep(Duration::from_secs(delay_secs)).await;
        }
    }

    unreachable!("Loop should have returned or errored")
}

const NASDAQ_BASE_URL: &str = "https://data.nasdaq.com/api/v3/datatables";

const MAX_RETRIES: u32 = 3;

const INITIAL_TIMEOUT: u64 = 60;

async fn http_get_response(
    url: &str,
    headers: Option<&[(&str, &str)]>,
    query: Option<&[(&str, &str)]>,
    retries: u32,
    timeout_secs: Option<u64>,
) -> Result<reqwest::Response> {
    for attempt in 1..=retries {
        match get_request(url, headers, query, timeout_secs)?.send().await {
            Ok(response) if response.status().is_success() => return Ok(response),
            Ok(response) if attempt == retries => {
                return Err(anyhow!(
                    "HTTP request failed with status {} after {} attempts",
                    response.status(),
                    retries
                ));
            }
            Err(e) if attempt == retries => {
                return Err(anyhow!("Request failed after {} attempts: {}", retries, e));
            }
            _ => {}
        }

        if attempt < retries {
            let delay_secs = 2_u64.pow(attempt - 1);
            sleep(Duration::from_secs(delay_secs)).await;
        }
    }

    unreachable!("Loop should have returned or errored")
}

/// Resolves a NASDAQ datatable export URL and returns a ZIP byte stream.
///
/// # Failure
/// Returns an error if export metadata retrieval or ZIP download fails after retries.
pub async fn nasdaq_api_get(
    path: &str,
    api_key: &str,
    query: Option<&HashMap<String, String>>,
) -> Result<impl Stream<Item = reqwest::Result<bytes::Bytes>>> {
    let base_url = format!("{}/{}", NASDAQ_BASE_URL, path);

    let mut query_params = Vec::with_capacity(2 + query.as_ref().map_or(0, |q| q.len()));
    query_params.push(("api_key", api_key));
    query_params.push(("qopts.export", "true"));

    if let Some(extra_params) = query {
        query_params.extend(extra_params.iter().map(|(k, v)| (k.as_str(), v.as_str())));
    }

    for attempt in 1..=MAX_RETRIES {
        let response = http_get(
            &base_url,
            None,
            Some(&query_params),
            1,
            Some(INITIAL_TIMEOUT),
        )
        .await;

        let response = match response {
            Ok(r) => r,
            Err(e) if attempt == MAX_RETRIES => {
                return Err(anyhow!(
                    "HTTP request failed after {} attempts: {}",
                    MAX_RETRIES,
                    e
                ));
            }
            Err(_) => {
                let delay_secs = 2_u64.pow(attempt - 1);
                sleep(Duration::from_secs(delay_secs)).await;
                continue;
            }
        };

        let text = match response.into_text() {
            Ok(t) => t,
            Err(e) if attempt == MAX_RETRIES => {
                return Err(anyhow!(
                    "Failed to read response text after {} attempts: {}",
                    MAX_RETRIES,
                    e
                ));
            }
            Err(_) => {
                let delay_secs = 2_u64.pow(attempt - 1);
                sleep(Duration::from_secs(delay_secs)).await;
                continue;
            }
        };

        let json: Value = match serde_json::from_str(&text) {
            Ok(j) => j,
            Err(e) if attempt == MAX_RETRIES => {
                return Err(anyhow!(
                    "Failed to parse JSON after {} attempts: {}",
                    MAX_RETRIES,
                    e
                ));
            }
            Err(_) => {
                let delay_secs = 2_u64.pow(attempt - 1);
                sleep(Duration::from_secs(delay_secs)).await;
                continue;
            }
        };

        let download_url = json
            .pointer("/datatable_bulk_download/file/link")
            .and_then(Value::as_str)
            .filter(|url| !url.is_empty());

        let download_url = match download_url {
            Some(url) => url,
            None if attempt == MAX_RETRIES => {
                return Err(anyhow!(
                    "No valid bulk download link found after {} attempts",
                    MAX_RETRIES
                ));
            }
            None => {
                let delay_secs = 2_u64.pow(attempt - 1);
                sleep(Duration::from_secs(delay_secs)).await;
                continue;
            }
        };

        match http_get_response(download_url, None, None, 3, None).await {
            Ok(zip_resp) => return Ok(zip_resp.bytes_stream()),
            Err(e) if attempt == MAX_RETRIES => {
                return Err(anyhow!(
                    "Failed to download zip file after {} attempts: {}",
                    MAX_RETRIES,
                    e
                ));
            }
            Err(_) => {
                let delay_secs = 2_u64.pow(attempt - 1);
                sleep(Duration::from_secs(delay_secs)).await;
            }
        }
    }

    unreachable!("Loop should have returned or errored")
}

/// Fetches and saves a Logo.dev image for the given ticker symbol.
///
/// # Failure
/// Returns an error if the format is invalid, credentials are missing, or network or file I/O fails.
pub async fn get_logodev_api(
    symbol: &str,
    size: Option<u32>,
    format: Option<&str>,
) -> Result<String> {
    use std::env;

    let size = size.unwrap_or(100);
    let format = format.unwrap_or("png");
    let symbol = symbol.to_uppercase();

    if format != "png" && format != "webp" {
        return Err(anyhow!(
            "Invalid format '{}'. Only 'png' and 'webp' are supported.",
            format
        ));
    }

    let logo_key = env::var("LOGO_KEY").map_err(|_| {
        anyhow!("LOGO_KEY environment variable not found. Please set your Logo.dev API token.")
    })?;

    let url = format!(
        "https://img.logo.dev/ticker/{}?token={}&size={}&fallback=monogram&retina=true&format={}",
        symbol, logo_key, size, format
    );

    let response = http_get(&url, None, None, 3, Some(30))
        .await
        .map_err(|e| anyhow!("Failed to fetch logo for {}: {}", symbol, e))?;

    let filepath = Path::new("output")
        .join("logos")
        .join(format!("{symbol}.{format}"));

    save_file(response.body.as_ref(), &filepath)?;

    Ok(filepath.to_string_lossy().into_owned())
}
